### ISSUE TITLE
Output signal of step pin misses one edge per movement

### ISSUE THREAD

**Issue by cedricwritescode** [eldendiss/DendoStepper#13]
**Describe the bug**
I noticed that the position of my stepper motor changes over time when I tried turning one full rotation repeatedly. Turns out, the ISR misses one flank per executed movement.

**To Reproduce**
Use example with any step count (a lower step count makes it more easily visible)
I used the following code:
```
#include <stdio.h>
#include "DendoStepper.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"

DendoStepper step;
DendoStepper step1;

extern "C" void app_main(void)
{

    DendoStepper_config_t step_cfg = {
        .stepPin = 2,
        .dirPin = 4,
        .enPin = 5,
        .miStep = MICROSTEP_1,
        .stepAngle = 1.8};

    step.config(&step_cfg);

    step.init();

    step.setSpeed(1000, 50, 50);

    step.setStepsPerMm(10);

    while (1)
    {
        //can't do 1 or 2 steps, it will not move!!
        step.runPos(10);
        vTaskDelay(8000 / portTICK_PERIOD_MS);
    }
}
```

**Expected behavior**
One movement produces the exact amunt of negative and positive edges (in my case 10 negative edges).

**Screenshots**
The existing code causes this behavior:
![old](https://github.com/eldendiss/DendoStepper/assets/41518201/6510bec0-96d3-42bc-85da-f5b0b10a604c)

Changing the ISR results in the correction of this issue:
![new2](https://github.com/eldendiss/DendoStepper/assets/41518201/0b5dd4cb-0614-4a40-b310-bbe482097d5f)

**HW (please complete the following information):**
 - ESP32 Wroom Devkit (ESP-WROOM-32)
 - Stepper driver: DM542T

**Pull Request**
See [here](https://github.com/eldendiss/DendoStepper/pull/14)

**Comment by eldendiss** [comment]
Merged. See #14
